'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, ShieldCheck, Truck } from 'lucide-react';
import Link from 'next/link';
import './buy.css';

const products=[
  ['Nexxus Adaptive Cleanse','Personalized cleanser',899,'Your cleanse step, matched to your profile.'],
  ['Nexxus Adaptive Condition','Personalized conditioner',999,'Conditioning tuned to your current needs.'],
  ['Nexxus Adaptive Treatment','Personalized treatment',1299,'Your targeted treatment step.']
];

export default function Buy({go}){
 const [sub,setSub]=useState(true),[freq,setFreq]=useState('Every 8 weeks'),[confirmed,setConfirmed]=useState(false);
 const total=products.reduce((a,p)=>a+p[2],0),discounted=sub?Math.round(total*.92):total;
 if(confirmed) return <main className="buy-page"><div className="buy-nav"><Link href="/"><ArrowLeft size={15}/> Back to Nexxus</Link><b>NEXXUS <small>YOUR ROUTINE</small></b><span>Order confirmed · Prototype</span></div><section className="buy-hero" style={{minHeight:'72vh',alignItems:'center'}}><div><label>YOUR ROUTINE IS ON ITS WAY</label><h1>Made for your hair.<br/><i>Now ready to become your routine.</i></h1><p>Your personalized Nexxus routine has been confirmed. Your Hair Intelligence profile will continue learning from your experience.</p><button className="buy-button" onClick={()=>go?go('dashboard'):window.location.href='/dashboard'}>GO TO MY NEXXUS <ArrowRight size={16}/></button></div><aside><span>ORDER CONFIRMED</span><strong>NX-2026-08120</strong><small>Personalized routine · {sub?'Subscription':'One-time'}</small></aside></section></main>;
 return <main className="buy-page"><div className="buy-nav"><Link href="/"><ArrowLeft size={15}/> Back to Nexxus</Link><b>NEXXUS <small>YOUR ROUTINE</small></b><span>Secure checkout · Prototype</span></div><section className="buy-hero"><div><label>YOUR ROUTINE IS READY</label><h1>Made for your hair.<br/><i>Ready for your routine.</i></h1><p>Your personalized recommendation is now a routine you can actually use. Review your products, choose how you want to receive them, and make it yours.</p></div><aside><span>PERSONALIZED FOR</span><strong>Your Hair Intelligence profile</strong><small>Profile match · 95%</small></aside></section><section className="buy-grid"><div><div className="buy-head"><div><span>01 · YOUR ROUTINE</span><h2>Three steps. One routine.</h2></div></div>{products.map((p,i)=><div className="product" key={p[0]}><div className="product-visual"><span>0{i+1}</span><b>N</b></div><div><small>{p[1]}</small><h3>{p[0]}</h3><p>{p[3]}</p><strong>Personalized formula <em>₹{p[2].toLocaleString('en-IN')}</em></strong></div></div>)}<div className="note"><Check size={16}/><span><b>Why these?</b> Your profile, goals and environment informed this routine. Your next recommendation can change as Nexxus learns from your feedback.</span></div></div><aside className="order"><span>YOUR ORDER</span><h2>Personalized routine</h2>{products.map(p=><div className="line" key={p[0]}><span>{p[0]}</span><b>₹{p[2].toLocaleString('en-IN')}</b></div>)}<div className="toggle"><button className={sub?'on':''} onClick={()=>setSub(true)}>Subscribe & save</button><button className={!sub?'on':''} onClick={()=>setSub(false)}>One-time</button></div>{sub&&<div className="frequency"><span>Delivery frequency</span><button onClick={()=>setFreq(freq==='Every 8 weeks'?'Every 6 weeks':'Every 8 weeks')}>{freq}<ChevronDown size={14}/></button></div>}<div className="total"><div><span>Subtotal</span><b>₹{total.toLocaleString('en-IN')}</b></div>{sub&&<div><span>Subscription saving</span><b>−₹{(total-discounted).toLocaleString('en-IN')}</b></div>}<div className="grand"><span>Today</span><b>₹{discounted.toLocaleString('en-IN')}</b></div></div><button className="buy-button" onClick={()=>setConfirmed(true)}>BUY MY ROUTINE <ArrowRight size={16}/></button><small className="trust"><ShieldCheck size={14}/> Secure checkout &nbsp; <Truck size={14}/> Delivery included</small></aside></section></main>;
}
